name: Run NTTT tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.7"
          - os: windows-latest
            python: "3.7"
          - os: macos-latest
            python: "3.11"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test
        run: |
          python -m unittest discover -s unit_test/ -v
